### ISSUE TITLE
BGP and OSPFv2/v3 router-id generation

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#148]
Currently, sros and srlinux use the ipv4 loopback ip as router-id.
This means that loopback.ipv4 must always be defined.
Should this determination be moved to core logic (bgp module)?
Same for the rr cluster-id (currently hardcoded to loopback.ipv4 in several places)

Furthermore, the bgp template generates both ipv4 and ipv6 peerings to the same neighbor; should there be a preference (in the BGP logic) and do we need a way to disable peering on ipv4 or ipv6?

**Comment by ipspace** [comment]
Interesting. Never thought about that. What happens when you try to run OSPF and BGP in an IPv6-only network?

We could add "router_id" (or should it be just "id"?) calculation to BGP and OSPF modules, which would also make it configurable via topology file. I wonder what happens if you use "0.0.0.id" as router ID (in case it's not configured and the loopback interface is not set). Implementations that understand it's just a 32-bit number won't have a problem (plus we'd avoid any potential overlap with lab addressing).

As for parallel ipv4 and ipv6 peerings, that's the sanest way of configuring multi-vendor dual-stack BGP. From the topology transformation perspective I have to check what happens in v6-only network. From the BGP design perspective, if someone wants to have something different (like Cumulus running IPv4 AF over IPv6 LLA session), they could always write a plugin ;)

**Comment by jbemmel** [comment]
Although one could configure a different router_id for BGP and OSPF, I think it makes the most sense if it is the same.
I could add the 'loopback.ipv4|default(...)' logic to the templates, but I would prefer to have the 'initial' module do the honors
(or perhaps the 'augment' logic where loopbacks get calculated)

In my ipv6-only topology only the ipv6 BGP session comes up. If you say it's the sanest way to try both by default that's fine, but I'd still like a flag to say "don't configure ipv4 peers for bgp"

Perhaps
```
bgp:
 peering:
  ipv4: False
```

**Comment by ipspace** [comment]
Ah, so you configured IPv4 loopbacks in an IPv6-only network (to get router IDs) and all of a sudden you have a bunch of IBGP IPv4 sessions. Yeah, that sucks ;)

I like the idea of controlling which sessions one wants to have (and we could extend it to EVPN or L3VPN sometime), but I think we need to have IBGP and EBGP parts, for example:

```
bgp:
 peering:
  ibgp:
   ipv4: False
```

**Comment by jbemmel** [comment]
I think the BGP session (ipv4 and/or ipv6) and the address families to enable are 2 different things

The current logic is like this:
```
    # Calculate BGP address families
    for af in ['ipv4','ipv6']:
      for n in node.bgp.neighbors:
        if af in n:
          node.bgp[af] = True
          break
```

in other words, if a node has an ip address for the given family, enable that family.

Shall we add something like this?
```
bgp:
  address-families: [ ipv4, ipv6 ]
```

(to be extended with evpn, etc once we get to it )

**Comment by ipspace** [comment]
After mulling this over for a few days: it looks like you tried to build an IPv6-only network, failed at BGP router ID, fixed that with IPv4 addresses on loopback interfaces, and then got to the point where you had those annoying IPv4 IBGP sessions that would never come up.

The root cause is obviously the missing router ID, and we should fix that so people can build an IPv6-only network. As you rightfully pointed out, **bgp.router_id** computed in Python is the right way to go. It could be configured manually, copied from loopback IPv4 address, or generated from an ID pool.

I'd propose we add a **router_id** pool to the predefined addressing pools, and use it in the same way we use the **loopback** pool for loopbacks to generate router IDs. Have to check, but it might be OK to use the same IPv4 range for both pools.

Have I missed anything (moving BGP peering/AF discussion into another issue)?

**Comment by jbemmel** [comment]
Agreed, router_id pool which defaults to the same range as loopback sounds good to me

**Comment by ipspace** [comment]
Implemented router IDs and modified the configuration templates for IOS, NXOS, EOS, Cumulus v4, FRR and Junos

Router ID is calculated during the post_node_transform module processing and results in **node.router_id**, **node.ospf.router_id** and **node.bgp.router_id** being a valid IPv4 address. You can use **ospf.router_id** or **bgp.router_id** in configuration templates.

@jbemmel: Could you add the necessary logic to SR OS and SR Linux templates?
@ssasso: Does it make sense to implement that for RouterOS and VyOS? It's absolutely not a problem if some devices don't implement configurable **router_id** (will add another column to feature support table)
@petercrocker: Does Fortinet support something along these lines in OSPF?

**Comment by ssasso** [comment]
@ipspace I will add it for both RouterOS and VyOS (and for both the protocols)!

**Comment by petercrocker** [comment]
Fixed for Cumulus NVUE and Fortinet:
https://github.com/ipspace/netsim-tools/pull/183
