### ISSUE TITLE
Minimal Ansible version 2.9.1 in requirements.txt

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#162]
I was using Ansible 2.9.0 and hit a bug when trying to deploy FRR: https://github.com/ansible/ansible/pull/64070

Upgrading to 2.9.1 fixed it - we may want to put that as a requirement

**Comment by ipspace** [comment]
Ansible is not a _netsim-tools_ requirement on purpose - I already had people who wanted to use the transformation tool but not Ansible (or **ansible-inventory**), that's why I implemented the **devices.yml** file.

The best I can do is add a note to **install.md** (done)

**Comment by jbemmel** [comment]
'extras' are designed for this: https://www.python.org/dev/peps/pep-0508/#extras

see e.g. https://godatadriven.com/blog/a-practical-guide-to-using-setup-py/

```
setup(
    name='example',
    version='0.1.0',
    packages=find_packages(include=['exampleproject', 'exampleproject.*']),
    install_requires=[
        'PyYAML',
        'pandas==0.23.3',
        'numpy>=1.14.5'
    ],
    extras_require={
        'ansible': ['ansible>=2.9.1'],
    }
)
```

**Comment by ipspace** [comment]
Thank you -- will think about that.

The real problem I have with Ansible are numerous semi-specified dependencies required by individual device modules. For example, Junos modules require lxml. That's why I prefer to install it separately.

Speaking of semi-specified dependencies: if I install nokia.grpc collection it crashes because I don't have whatever prerequisite modules that are not specified anywhere in the documentation. Bummer...
