### ISSUE TITLE
Community edition of Cumulus VX 5.0.1 is gone

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#260]
CumulusCommunity/cumulus-vx:5.0.1 is no longer available on Vagrant Cloud, and the box downloadable from NVIDIA web no longer contains the metadata information that would indicate VX version. The only way forward I can see is to:

* Change virtualbox/libvirt image to `cumulus/vx5` similar to juniper/vsrx3 (who knows when a similar shenanigan will happen to Cumulus VX 4.4)
* Add installation instructions similar to Arista EOS or Cisco Nexus OS to netsim-tools documentation

Unless someone has a good reason why we shouldn't do it this way, I'll make the necessary changes before release 1.2.2 ships.

CC: @ssasso @petercrocker @barajus

**Comment by ssasso** [comment]
Thanks @ipspace ! I agree with the two points above (and with the naming).

But the installation would be a bit different than Arista or Cisco (if you meant https://netsim-tools.readthedocs.io/en/latest/labs/eos.html and https://netsim-tools.readthedocs.io/en/latest/labs/nxos.html), since only the "vagrant box add" seems to be required.
It would be more like the Arista box section on this page: https://netsim-tools.readthedocs.io/en/latest/tutorials.html#preparing-the-network-device-images

**Comment by petercrocker** [comment]
I just confirmed with the Cumulus guys it’s an engineering mistake. It’s being re-uploaded shortly to vagrant’s public box listings. So don’t do anything, should be fixed shortly!

**Comment by petercrocker** [comment]
It’s back up: https://app.vagrantup.com/CumulusCommunity/boxes/cumulus-vx

**Comment by ipspace** [comment]
> I just confirmed with the Cumulus guys it’s an engineering mistake. It’s being re-uploaded shortly to vagrant’s public box listings. So don’t do anything, should be fixed shortly!

Thanks for the feedback. Let's hope it stays that way, otherwise we have a fallback solution. Closing this one... hopefully "forever"
