### ISSUE TITLE
SR Linux VLAN implementation should not use vlan_name

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#290]
@jbemmel: I noticed you're using `vlan_name` in SR Linux configuration templates. That parameter is used to identify all nodes connected to the same VLAN (to set the neighbor list correctly) and could be set even on nodes that don't use VLANs or interfaces that are not access/trunk interfaces. I was not sure what you were trying to do in that template, so I didn't dare touching it.

I hope the just-created VLAN developer documentation https://netsim-tools.readthedocs.io/en/dev/dev/config/vlan.html does a better job explaining what parameters are safe to use in configuration templates.

Finally, 0defd8e963a53ca6889d23e164f490199e974b41 added support for routed VLAN subinterfaces. It would be nice to have them in SR Linux if it supports that concept.

**Comment by jbemmel** [comment]
@ipspace this is due to the way SVI interfaces are configured on SR Linux. All other systems have svi_interface_name with 'vlan' or 'bvi', but I need to know the physical parent interface ( e.g. ethernet-1/1 ) and the VLAN id. I didn't like putting a composite string value in the interface name, to then break it up again in the template logic, so I opted to use 'vlan_name' to lookup the id

I can do
```
svi_interface_name: "{ifname}.{vlan}"
```
in topology-defaults.yml and then retrieve the VLAN id from there, instead of via 'vlan_name' - but I would personally prefer to either have some reference to a vlan attribute structure, or the vlan.id attribute included explicitly (rather than via a platform-specific templated string kludge)
