### ISSUE TITLE
ContainerLab OCI provider test

### ISSUE THREAD

**Issue by bbros-dev** [ipspace/netsim-tools#33]
The current CL provider test appears to be a VM?
Anyway it didn't help us we tried to understand what and how things worked.... so we think this indicates a test is required?
PR forthcoming.

**Comment by ipspace** [comment]
There are no automated integration tests at the moment. The tests run by GitHub actions include sanity checks (mypy) and the data model transformation tests (expected results, expected errors...).

It's questionable whether it's worth running the automated integration tests at all, as 90+% of the cases a typical user would be interested in cannot be executed in a third-party environment due to licensing issues. I'm creating the integration tests so I can run them on a bare-metal server with pre-provisioned NOS images.

I think we're back to the "what is the use case" discussion ;)
