### ISSUE TITLE
Handling of group- and node 'config' option should be moved to 'netlab initial'

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#77]
The custom deployment templates (**config** option) are implemented in `netlab up` code. They should be moved to `netlab initial`.

Challenge: the code implementing the **config** option should have access to topology file, and right now **netlab initial** does not need it.

Suggested workaround:

* Merge group- and node **config** option when processing group data
* Optional: rename node **config** option into **netsim_config** inventory variable (set up the framework to do it properly)
* Expand the _initial config deployment_ Ansible playbook to go through the **netsim_config** list similar to how it traverses module list

**Comment by jbemmel** [comment]
Associated with this, some node/provider types can support a different provisioning model where the config file is bind-mounted to a container (instead of executed after bringing up the node)

For example, in Containerlab there is a 'startup-config' option that could point to a generated file - but this is currently not possible due to the order of processing steps.

Perhaps we could generalize the model, separate the generation of the config file from its deployment and allow providers/nodes to indicate which provisioning model is desired?

Containerlab builds a directory structure with a subdir for each node, and puts the (initial) config there. The config can be updated and saved to the same place, providing an easy way to save the configs of the complete topology. Something similar would be helpful for netsim-tools (instead of using temporary files and throwing them away, as is currently done)

**Comment by ipspace** [comment]
@jbemmel Moved the "creating config file" discussion to #80

**Comment by ipspace** [comment]
Implemented in f2be10a
