### ISSUE TITLE
Allow VM settings via user config file

### ISSUE THREAD

**Issue by petercrocker** [ipspace/netsim-tools#84]
Feature request:
Allow settings such as VM image, VM CPU count, VM memory to be overridden from defaults via a config file imported on the netlab command line options.

Use cases:

1) change libvirt mem for linux image from 512m to 1G or more. If you want to do any kind of testing on the linux boxes and install packages, you can quickly run out of memory.

2) choose a different Linux VM vagrant image to use other than the current generic ubuntu 20.04 image

3) allow two (or more) different kinds of Linux VMs to be spun up:
- Linux very simple host (ping, tcpdump)
- Linux VM to run services on (netflow collector, ansible tower, netbox + db, etc.)
- I want to specify some Linux VMs as the first simple role, and other VMs in the topology to have more mem/cpu for the second role

**Comment by ipspace** [comment]
You can already specify the 'image' or 'box' attribute in node (or **node_data** within a group). Maybe it should be better documented (tell me). 

That addresses (2) and (3) apart from "more mem/cpu" which is identical to (1) -- the real challenge we have to work on.

**Comment by ipspace** [comment]
@petercrocker Implemented two mechanisms in **cpu** branch:

* Override default settings in provider Jinja2 template. It's a bit cumbersome as you cannot use `|default(x)` Jinja2 filter on Boxes with `default_box=True` -- an empty dictionary is created the moment the value is touched (implemented for **linux** device).
* Add `provider_cpu` and `provider_memory` settings to **devices** defaults, making sure **cpu** and **memory** are always set in the node data (implemented for **cumulus** device)

I sort-of like the first approach because it doesn't pollute the node data, but it's a hassle to implement in the template, so I can't decide which way to go.

If you feel like fixing other devices please start with the **cpu** branch and submit a PR against the **dev** branch. I plan to merge this with the **dev** branch and push out a new release before the year-end, but of course we can always fix other devices later (if needed).

**Comment by ipspace** [comment]
This one will be implemented after we figure out how to do #138.

**Comment by ipspace** [comment]
@petercrocker @ssasso: Now that we have #138 and #140 done, I started thinking about doing this _the right way_:

* Specify **vcpu** and **memory** as node attributes
* Set **vcpu** and **memory** values in **defaults.devices** (per device or per provider within a device)
* Modify **Vagrantfile** templates to check for presence of **vcpu** and **memory** and set them in the common part of the template instead of individual device templates.

Any thoughts?

**Comment by petercrocker** [comment]
@ipspace I'd agree with the approach of having vcpu and memory as both a per-device and global setting, and here's why:

- most people have limited RAM (many desktop-class CPUs top out with 32G), so you'll want to squeeze as much in there as possible
- Cases where you could want per-node memory/cpu:
  - JunOS vSRX as a pure P node (no bgp) you could get away with 2G, but if it's a PE you need 4G
  - Linux hosts as endpoints could use 512M but if I want to run an AAA server, or prometheus/granana, I need 2G for that one specific host

**Comment by ipspace** [comment]
Implemented. Details in 8d1b860 commit message and documentation.
